apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgresql-secrets.yaml
  - postgresql-pvc.yaml
  - redis-password.yaml
  - authentik-secretkey.yaml
  # - arr-ingress.yaml
