controller:
  service:
    containerPort:
      http: 80
      https: 443
      ldap: 389
      ldaps: 636
    loadBalancerIP: "192.168.18.150"
    annotations:
      tailscale.com/expose: "true"
  extraArgs:
    "default-ssl-certificate": "cert-manager/kopi-quest-tls"
  
  ingressClassResource:
    name: nginx
    default: true
    controllerValue: k8s.io/ingress-nginx
  
  ingressClass: nginx
